version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: debefix-sample-app
      POSTGRES_USER: sample_user
      POSTGRES_PASSWORD: sample_password
    ports:
      - 5438:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
