with-expecter: True
log-level: warn
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
packages:
  github.com/rrgmc/debefix-sample-app/internal/storage:
    interfaces:
      TagStorage:
      CountryStorage:
      UserStorage:
